### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by shaheenp** [wgreenberg/quine.zip#3]
This bug occurs when a repeat command is executed with N = 0 (e.g. `repeat 1 0`).

It occurs on [src/interpreter.js#L81](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L81). In [this code block](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L97), `start` ends up equaling 1 because `outputLines` is an array of 1 item and `instructions.b` is 0. Because `start` is 1, the loop is accessing `outputLines[1]`, which is `undefined` because `outputLines` has only 1 item, but the value still gets pushed to `outputLines`. `program` at that point is an empty array, so [src/interpreter#L90](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L90) gets executed. Remember that `outputLines` is an array of `[/*previous action {String}*/, undefined]`. Now we're back at [src/interpreter.js#L81](https://github.com/wgreenberg/quine.zip/blob/gh-pages/src/interpreter.js#L81), where `undefined.length` throws the error.

Hopefully that made sense...
Here are some examples that throw the error:

``` js
print 1
print 1
repeat 1 0

// OR

print 2
print 1
print 1
repeat 3 0

// OR

print 1
print 3
repeat 2 0
print 2
```

**Comment by wgreenberg** [comment]
Good catch, thanks! If you wouldn't mind, adding those examples to the unit tests would be super helpful as well :)

**Comment by shaheenp** [comment]
will do!

**Comment by shaheenp** [comment]
@wgreenberg added the test

**Comment by wgreenberg** [comment]
Looks good, thanks @shaheenp!
